apiVersion: v1
kind: Service
metadata:
  name: go-social-service-staging
spec:
  selector:
    app: go-social-service-staging
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
