openapi: "3.0.2"
info:
  title: "Social Service API"
  description: "Service API for social service APP"
  version: "1.0"
servers:
  - url: "http://localhost:4000/api"
paths:
  /users:
    post:
      tags:
        - "User Management"
      summary: "Create a new user"
      description: "Endpoint to create a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                email:
                  type: "string"
                  format: "email"
                password:
                  type: "string"
                  format: "password"
      responses:
        "201":
          description: "User created successfully"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "integer"
                  username:
                    type: "string"
                  email:
                    type: "string"
                  createdAt:
                    type: "string"
components: {}
